### ISSUE TITLE
Does Django-Multitenant support Python 3?

### ISSUE THREAD

**Issue by ReneFroger** [citusdata/django-multitenant#120]
I'm interested in this package, because the option (isolated schema) seems to be overengineered. My SAAS app hasn't not even a customer. I believe I should do what I need to survive next week or next quarter and don't overengineer for a problem I don't have yet.

So I'm going for this package. However, regarding [the list of Django packages
](https://djangopackages.org/grids/g/multi-tenancy/) this package couldn't be stable and wasn't ready for Python 3? So I wonder if there is some truth to that?

**Comment by JelteF** [comment]
It seems the website you are looking at has out of date information: 
> Aug. 25, 2020, 8:44 a.m.

The latest version of this package is marked as Production/Stable and is actually Python 3 only (so no python 2 support at all anymore)
