### ISSUE TITLE
regression with citus distribution migrations being in a different app than the model's app

### ISSUE THREAD

**Issue by maziar-dandc** [citusdata/django-multitenant#123]
Regression happened in: https://github.com/citusdata/django-multitenant/commit/beffbf2025664d4f5f56eb2159e2ac7c2f1af545
Bug fix: https://github.com/Digital-and-Code-UK-Ltd/django-multitenant/commit/30e937d9e5b5158969b57f579a0a9045e8921ffc

Expected behavior: models being distributed properly
Actual behavior: models were being distributed as reference tables because they weren't found in get_models() of migration app_label

![image](https://user-images.githubusercontent.com/53433222/154643013-9672add8-c598-4ab8-9b33-d6072b5477fd.png)

**Comment by JelteF** [comment]
Hmm, that does not sound good. Could you make a pull request with your changes?
