### ISSUE TITLE
DOCS: Supported Django and Citus versions/Pre-requisites

### ISSUE THREAD

**Issue by paxw-panevo** [citusdata/django-multitenant#174]
Looking at the section "Supported Django and Citus versions/Pre-requisites", https://django-multitenant.readthedocs.io/en/latest/general.html

It looks like if you have python 3.9 then installing django_multitenant shouldn't work with an application that has django 3.2

However, installing django-multitenant works fine.

**Proposal**: I'd need to know what the expected behaviour is. I'm happy to create a PR to (a) update documentation so it has the correct matrix (b) Update how dependencies are specified so unsupported python or django versions will NOT work.

**Comment by gurkanindibay** [comment]
Thanks @paxw-panevo . I added tests and updated the support matrix now with the PR #188
