### ISSUE TITLE
Release 4.1.0 overwrote 4.0.0 wheel

### ISSUE THREAD

**Issue by hrother** [citusdata/django-multitenant#205]
It looks like the publication of the 4.1.0 release overwrote the 4.0.0 wheels on pypi.

![image](https://github.com/citusdata/django-multitenant/assets/120819/cd14e91c-369a-47f4-9d8a-531acba93d2c)

The broken 4.0.0 wheel now produces this error:

```python
AttributeError: 'Settings' object has no attribute 'TENANT_USE_ASGIREF'
```

The asgiref support should not be part of 4.0.0 but only of 4.1.0.

**Comment by rzwink** [comment]
We needed to add TENANT_USE_ASGIREF = False
to our applications settings.py to avoid an error we were getting after the happened.  FYI.

**Comment by hrother** [comment]
I'm sorry but I do not think this issue is fixed yet.

The 4.0.0 wheel on pypi still contains the source code of the 4.1.0 release.

Therefore all django applications which have pinned django-multitenant to 4.0.0 will break when they are reinstalled/redeployed.

@gurkanindibay is it possible to recreate the 4.0.0 wheel and upload it to pypi?
