### ISSUE TITLE
Support sub-domains?

### ISSUE THREAD

**Issue by allidoisace** [citusdata/django-multitenant#25]
Does this package support the use of sub-domains or does this need to be implemented separstely or with another package like django-subdomains or django-hosts?

**Comment by gurkanindibay** [comment]
This project is on Django ORM and does not have any feature for view or template layer.
This project aims to manage the multitenant lifecyle in moswl layer. If you need multitenancy in view or template layer,
you can perform model layer using django-multitenant and integrate your views and templates into the model layer using API's provided by django-multitenant
Thanks
