### ISSUE TITLE
The create() method does not fill in tenant id

### ISSUE THREAD

**Issue by begriffs** [citusdata/django-multitenant#3]
In my app Store is the tenant. Trying to create a product

```python
s = Store.objects.get(id=1)
set_current_tenant(s)
Product.objects.create(name="nice product", description="buy me", quantity = 1)
```

The result is

```
django.db.utils.DataError: cannot perform an INSERT with NULL in the partition column
```

**Comment by gilsonbp** [comment]
@begriffs you need a MIDDLEWARE like this to identify the user's tenant but it will only serve for queries:
<img width="584" alt="captura de tela 2017-12-19 as 11 27 23" src="https://user-images.githubusercontent.com/2508305/34161837-94813fae-e4b0-11e7-965c-6228ec57ba30.png">

To add a new record you will need to inform the current tenant:
`
Product.objects.create(name="nice product", description="buy me", quantity = 1, tenant_id=get_current_tenant())
`
