### ISSUE TITLE
does this support MySQL??

### ISSUE THREAD

**Issue by heimagithub** [citusdata/django-multitenant#33]
My project database uses MySQL. I want to switch schemas dynamically. so can it support MySQL???

**Comment by louiseGrandjonc** [comment]
Hello @heimagithub,

I have never tested this project with MySQL. 
The goal is mainly to add `AND tenant_id=X` and change the join to be 
`SELECT * FROM table_a JOIN table_b ON (table_a.id=table_b.a_id AND table_a.tenant_id=table_b.tenant_id)`, these queries being compatible with MySQL, I see no problem in terms of compatibility.

The only thing is that the database engine being based on the postgresql one, you should not change it like the documentation says :) It will work anyway 

Let me know if you tried and if it works !
