### ISSUE TITLE
Attribute Error 'Store' object has no attribute 'tenant_id'

### ISSUE THREAD

**Issue by divick** [citusdata/django-multitenant#37]
I have cloned master branch to use django_multitenant so as to have django_multitenant.backends.postgresql available as Engine to me. But on doing so as soon as I try to create an object in database, it throws this exception. The exception happens because it is trying to access tenant_id attribute on Tenant model. The documentation does not say that tenant_id needs to be set on the tenant model too (Store model).

Offending line:

```
 current_tenant_id = getattr(current_tenant, current_tenant.tenant_id, None) 
```

The variable at this point are:

```
current_tenant | <Store: MyStore>
queryset | <TenantQuerySet [<UserProfile: UserProfile object (7)>]>
self | <django_multitenant.models.TenantManager object at 0x7f9638dfe940
````

And UserProfile looks something like this:

```
class UserProfile(TenantModel):
...
...
store = models.ForeignKey(Store, on_delete=models.CASCADE, null=True)
tenant_id = 'store_id'

class Meta:
    unique_together = ['id', 'store']
```

Store model:

```
class Store(models.Model):
name = models.CharField(max_length=64, unique=True)
...
````

**Comment by louiseGrandjonc** [comment]
Hi,

indeed, it should be in the documentation. The Store model needs to have tenant_id = 'id' in its class.
