### ISSUE TITLE
Unable to import mixins

### ISSUE THREAD

**Issue by Dineshs91** [citusdata/django-multitenant#40]
I am trying to import mixins in my code.

```
from django_multitenant.mixins import *
```

I am getting this error `ModuleNotFoundError: No module named 'django_multitenant.mixins'`.

Python version: 3.6
Library version: 1.1.0

**Comment by Dineshs91** [comment]
This will fix the issue

In file ` django_multitenant/django_multitenant.py` add the following import

```
from .mixins import TenantManagerMixin, TenantModelMixin
```

**Comment by louiseGrandjonc** [comment]
Hi,

We haven't deployed the new version of the django-multitenant library on Pypi. So the `django_multitenant.mixins` will only be available if you use our master. Is it what you are doing or did you install it using pip?

**Comment by Dineshs91** [comment]
@louiseGrandjonc I installed the library using pip. I tried installing from the master branch now and it seems to be working. Thanks for the quick response.

When will the new version be deployed to Pypi ?

**Comment by louiseGrandjonc** [comment]
I think that I should be able to release the new version on Pypi this week :) I will let you know as soon as it's done

**Comment by louiseGrandjonc** [comment]
Hi @Dineshs91, I wanted to let you know that the version 2.0.0 of the django-multitenant library has been released.

**Comment by Dineshs91** [comment]
Thanks a lot.
