### ISSUE TITLE
Tags in github

### ISSUE THREAD

**Issue by ledburyb** [citusdata/django-multitenant#49]
Would it be possible to get release tags in GitHub for the corresponding PyPi versions? I've encountered a few issues with particular versions, specifically 2.0.5 and 2.0.6 and it would be easier to work out what's going on if I could see the changes between versions in git.

**Comment by louiseGrandjonc** [comment]
Hi @ledburyb, thank you for suggesting this. I created the tags.
https://github.com/citusdata/django-multitenant/tags

Could you let me know what errors you're having? I released fixes suggested in other tickets in the version 2.0.8

**Comment by ledburyb** [comment]
Hi @louiseGrandjonc, thanks for this.  Everything is working for me since 2.0.8 with the exception of migrations issues which I've mentioned in other tickets.

**Comment by louiseGrandjonc** [comment]
I am working on it in a new branch :) Once it is fixed I will publish it on
pypi and create a new tag!

Le ven. 17 mai 2019 à 13:25, Ben Ledbury <notifications@github.com> a
écrit :

**Comment by louiseGrandjonc** [comment]
Just a heads up, I renamed the . tags be v2.0.X instead of 2.0.X
