### ISSUE TITLE
Document examples for where to add set_current_tenant

### ISSUE THREAD

**Issue by saicitus** [citusdata/django-multitenant#5]
Give some examples of where to include calls to `set_current_tenant` - whether as part of a middleware or as part of the individual views themselves.

**Comment by gilsonbp** [comment]
MIDDLEWARE example where I check if the logged-in user has a connection with some host before.
<img width="584" alt="captura de tela 2017-12-19 as 11 27 23" src="https://user-images.githubusercontent.com/2508305/34161519-a6bfc880-e4af-11e7-80d1-0551d420836f.png">

**Comment by saicitus** [comment]
https://github.com/citusdata/django-multitenant#where-to-set-the-tenant
