### ISSUE TITLE
Incorrect guidance in docs

### ISSUE THREAD

**Issue by rob101** [citusdata/django-multitenant#80]
In the docs, the following is suggested:

```
     def process_response(self, request, response):
             set_current_tenant(None)
             return response
```

This means that the response has no tenant when returned, incapacitating the project. Presumably this should be removed? It is also now depreciated and would require `django.utils.deprecation.MiddlewareMixin`

**Comment by louiseGrandjonc** [comment]
Yes, you are right, this should be removed from the documentation.

**Comment by louiseGrandjonc** [comment]
Fixed in https://github.com/citusdata/django-multitenant/commit/1c908cb6fe18f83df07bf1441411cfe37fb20295
