### ISSUE TITLE
 No module named 'django_multitenant.db'

### ISSUE THREAD

**Issue by juggernut** [citusdata/django-multitenant#81]
Hello everyone , 
I followed the tutorial on : http://docs.citusdata.com/en/v9.1/develop/migration_mt_django.html
And when i arrived on the migration part (distribution) i discovered that the db module misses from the project .
So when you try to import like this:
"from django_multitenant.db import migrations as tenant_migrations"
I get the error:
"ModuleNotFoundError: No module named 'django_multitenant.db'"
I downloaded the tar.gz from version 2.00 to 2.09 and not even one had the 'db' module inside . 

I can do it manually but i would love to know what happened .

**Comment by louiseGrandjonc** [comment]
Hi @juggernut,

thank you for raising that issue. I fixed the error, a little problem with the setup.py and the packages. If you try version 2.1.1 it should be fixed!

**Comment by juggernut** [comment]
Thanks alot man! You saved my life !
