### ISSUE TITLE
Tenant not set when using bulk_create

### ISSUE THREAD

**Issue by rob101** [citusdata/django-multitenant#89]
Django doesn't call the `save()` method when using `bulk_create`; [per the docs](https://docs.djangoproject.com/en/3.0/ref/models/querysets/#django.db.models.query.QuerySet.bulk_create).

It looks like the [TenantModelMixin](https://github.com/citusdata/django-multitenant/blob/7b06e871950cb84e0521dd87e3260e249d377383/django_multitenant/mixins.py#L35) therefore doesn't set the current tenant on object creation via this method.

It may be worth adding this, or otherwise referring to the exception in the docs.

**Comment by louiseGrandjonc** [comment]
hi @rob101, I fixed it in the `2.3.1` release. Thank you for creating the issue.
