### ISSUE TITLE
If Tenant reference is named tenant, tenant_id collides

### ISSUE THREAD

**Issue by s4ke** [citusdata/django-multitenant#98]
We have models that have a tenant field set as `tenant = ....` and django therefore generates tenant_id as part of the django model. This collides with the usage of self.tenant_id.

To work around this, we have to manually override 

```
    @property
    def tenant_field(self):
        return 'tenant_id'
```

**Comment by s4ke** [comment]
This should either be documented as a workaround, or we should check if maybe accessing tenant_id via `cls.tenant_id` works instead.

**Comment by s4ke** [comment]
With the workaround in #99 in mind I don't think the proposed solution works. I think for our usecase will need to create custom Mixins?

**Comment by KrYpTeD974** [comment]
This workaround works really well, I've tested it on a big project. 

This is the base class of every tenant related models we have.
```
class TenantAwareModel(TenantModel):
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)

    @property
    def tenant_field(self):
        return 'tenant_id'

    class Meta:
        abstract = True
```

Big thank you to @s4ke !
And +1 about adding this workaround in the documentation.

**Comment by gurkanindibay** [comment]
For now, please change the tenant_id columns with different name. tenant_id is kind of reserved keyword. I will try to find a way to remove this constraint soon

**Comment by gurkanindibay** [comment]
@s4ke @KrYpTeD974 Fixed with the pr https://github.com/citusdata/django-multitenant/pull/151
